"""initial tables

Revision ID: ec276e6df19f
Revises: 
Create Date: 2026-03-23 15:31:49.926436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec276e6df19f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channel_pairs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tg_chat_id', sa.BigInteger(), nullable=False),
    sa.Column('express_chat_id', sa.Uuid(), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('express_chat_id'),
    sa.UniqueConstraint('tg_chat_id')
    )
    op.create_table('employees',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tg_user_id', sa.BigInteger(), nullable=True),
    sa.Column('express_huid', sa.Uuid(), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('position', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('tg_user_id IS NOT NULL OR express_huid IS NOT NULL', name='ck_employee_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('express_huid'),
    sa.UniqueConstraint('tg_user_id')
    )
    op.create_table('message_files',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('direction', sa.String(length=15), nullable=False),
    sa.Column('message_record_id', sa.Uuid(), nullable=False),
    sa.Column('file_type', sa.String(length=31), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('file_content_type', sa.String(length=127), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('s3_key', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_message_files_record', 'message_files', ['message_record_id', 'direction'], unique=False)
    op.create_index('ix_message_files_s3_key', 'message_files', ['s3_key'], unique=False, postgresql_where='s3_key IS NOT NULL')
    op.create_table('to_express',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('channel_pair_id', sa.Uuid(), nullable=False),
    sa.Column('tg_message_id', sa.BigInteger(), nullable=False),
    sa.Column('tg_chat_id', sa.BigInteger(), nullable=False),
    sa.Column('tg_user_id', sa.BigInteger(), nullable=False),
    sa.Column('tg_media_group_id', sa.String(length=255), nullable=True),
    sa.Column('express_sync_id', sa.Uuid(), nullable=True),
    sa.Column('reply_to_tg_message_id', sa.BigInteger(), nullable=True),
    sa.Column('event_type', sa.String(length=31), nullable=False),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tg_chat_id', 'tg_message_id', 'event_type', name='uq_to_express_idempotency')
    )
    op.create_index('ix_to_express_channel_pair_id', 'to_express', ['channel_pair_id'], unique=False)
    op.create_index('ix_to_express_express_sync_id', 'to_express', ['express_sync_id'], unique=False)
    op.create_index('ix_to_express_media_group', 'to_express', ['tg_media_group_id'], unique=False, postgresql_where='tg_media_group_id IS NOT NULL')
    op.create_index('ix_to_express_status_pending', 'to_express', ['status'], unique=False, postgresql_where="status = 'pending'")
    op.create_table('to_telegram',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('channel_pair_id', sa.Uuid(), nullable=False),
    sa.Column('express_sync_id', sa.Uuid(), nullable=False),
    sa.Column('express_chat_id', sa.Uuid(), nullable=False),
    sa.Column('express_user_huid', sa.Uuid(), nullable=False),
    sa.Column('tg_message_id', sa.BigInteger(), nullable=True),
    sa.Column('tg_chat_id', sa.BigInteger(), nullable=True),
    sa.Column('reply_to_express_sync_id', sa.Uuid(), nullable=True),
    sa.Column('event_type', sa.String(length=31), nullable=False),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('express_sync_id', 'event_type', name='uq_to_telegram_idempotency')
    )
    op.create_index('ix_to_telegram_channel_pair_id', 'to_telegram', ['channel_pair_id'], unique=False)
    op.create_index('ix_to_telegram_status_pending', 'to_telegram', ['status'], unique=False, postgresql_where="status = 'pending'")
    op.create_index('ix_to_telegram_tg_message', 'to_telegram', ['tg_chat_id', 'tg_message_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_to_telegram_tg_message', table_name='to_telegram')
    op.drop_index('ix_to_telegram_status_pending', table_name='to_telegram', postgresql_where="status = 'pending'")
    op.drop_index('ix_to_telegram_channel_pair_id', table_name='to_telegram')
    op.drop_table('to_telegram')
    op.drop_index('ix_to_express_status_pending', table_name='to_express', postgresql_where="status = 'pending'")
    op.drop_index('ix_to_express_media_group', table_name='to_express', postgresql_where='tg_media_group_id IS NOT NULL')
    op.drop_index('ix_to_express_express_sync_id', table_name='to_express')
    op.drop_index('ix_to_express_channel_pair_id', table_name='to_express')
    op.drop_table('to_express')
    op.drop_index('ix_message_files_s3_key', table_name='message_files', postgresql_where='s3_key IS NOT NULL')
    op.drop_index('ix_message_files_record', table_name='message_files')
    op.drop_table('message_files')
    op.drop_table('employees')
    op.drop_table('channel_pairs')
    # ### end Alembic commands ###
